# Generated by Django 5.2.3 on 2025-09-25 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('node_type', models.CharField(help_text='Type of node, e.g. board, class, subject, chapter, unit, section', max_length=64)),
                ('order', models.IntegerField(default=0, help_text='Order of the node among its siblings')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the node')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='curritree.treenode')),
            ],
            options={
                'ordering': ['parent_id', 'order', 'name'],
                'unique_together': {('parent', 'name', 'node_type')},
            },
        ),
    ]
