# Generated by Django 5.2.3 on 2025-09-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curritree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treenode',
            name='node_type',
            field=models.CharField(choices=[('board', 'Board'), ('competitive', 'Competitive Exam (JEE/CET)'), ('class', 'Class/Grade'), ('subject', 'Subject'), ('unit', 'Unit/Module'), ('chapter', 'Chapter/Topic'), ('section', 'Section')], help_text='Type of node, e.g. board, class, subject, chapter, unit, section', max_length=64),
        ),
    ]
