# Generated by Django 5.2.3 on 2025-11-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curritree', '0002_alter_treenode_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='treenode',
            name='marks',
            field=models.IntegerField(default=0, help_text='Marks allocated to this node'),
        ),
    ]
