# Generated by Django 5.2.3 on 2025-09-26 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curritree', '0002_alter_treenode_node_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('short_answer', 'Short Answer'), ('match', 'Match the Following'), ('true_false', 'True/False')], max_length=20)),
                ('question_text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curriculum_chapter', models.ForeignKey(blank=True, limit_choices_to={'node_type': 'chapter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapter_questions', to='curritree.treenode')),
                ('curriculum_subject', models.ForeignKey(limit_choices_to={'node_type': 'subject'}, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='curritree.treenode')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_options', to='quiz.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MatchPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_item', models.CharField(max_length=200)),
                ('right_item', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_pairs', to='quiz.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FillBlankAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=200)),
                ('is_case_sensitive', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_blank_answers', to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('pattern', models.CharField(choices=[('standard', 'Standard Pattern'), ('section_wise', 'Section-wise Pattern'), ('difficulty_wise', 'Difficulty-wise Pattern'), ('custom', 'Custom Pattern')], default='standard', max_length=20)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('instructions', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curriculum_subject', models.ForeignKey(limit_choices_to={'node_type': 'subject'}, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='curritree.treenode')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ShortAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_answer', models.TextField()),
                ('max_words', models.PositiveIntegerField(default=50)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_answer', to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.BooleanField()),
                ('explanation', models.TextField(blank=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='true_false_answer', to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('marks', models.PositiveIntegerField()),
                ('section', models.CharField(blank=True, max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='quiz.questionpaper')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('paper', 'question')},
            },
        ),
        migrations.CreateModel(
            name='QuestionPaperAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(default=dict)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questionpaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('paper', 'student')},
            },
        ),
    ]
