# Generated by Django 5.2.3 on 2025-09-26 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curritree', '0002_alter_treenode_node_type'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='curriculum_board',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'node_type': 'board'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_questions', to='curritree.treenode'),
        ),
        migrations.AlterField(
            model_name='question',
            name='curriculum_chapter',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'node_type': 'chapter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapter_questions', to='curritree.treenode'),
        ),
        migrations.AlterField(
            model_name='question',
            name='curriculum_subject',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'node_type': 'subject'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='curritree.treenode'),
        ),
    ]
