# Generated by Django 5.2.3 on 2025-09-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_curriculum_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
