# Generated by Django 5.2.3 on 2025-10-20 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curritree', '0002_alter_treenode_node_type'),
        ('quiz', '0003_question_is_published'),
        ('saas', '0006_organizationprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='curriculum_chapters',
            field=models.ManyToManyField(blank=True, help_text='The specific units, chapters, or sections covered by this paper (multiple selection enabled).', related_name='paper_chapters', to='curritree.treenode'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='saas.organizationprofile'),
        ),
    ]
