# Generated by Django 5.2.3 on 2025-10-20 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curritree', '0002_alter_treenode_node_type'),
        ('quiz', '0004_questionpaper_curriculum_chapters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='curriculum_subject',
            field=models.ForeignKey(limit_choices_to={'node_type': 'subject'}, on_delete=django.db.models.deletion.CASCADE, related_name='root_papers', to='curritree.treenode'),
        ),
    ]
