# Generated by Django 5.2.3 on 2025-10-25 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_questionpaper_curriculum_subject'),
        ('saas', '0006_organizationprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.organizationprofile'),
        ),
    ]
