# Generated by Django 5.2.3 on 2025-11-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_question_curriculum_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, help_text='Optional image to accompany the question text.', null=True, upload_to='questions/images/'),
        ),
    ]
