# Generated by Django 5.2.3 on 2025-11-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_questionuploadlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionuploadlog',
            name='upload_time',
        ),
        migrations.AlterField(
            model_name='questionuploadlog',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
