# Generated by Django 5.2.3 on 2025-11-27 18:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_question_question_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
