# Generated by Django 5.2.3 on 2025-11-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_question_question_uuid'),
        ('quiz', '0013_auto_20251127_2332'),
    ]

    operations = [
    ]
