# Generated by Django 5.2.3 on 2025-11-27 19:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curritree', '0003_treenode_marks'),
        ('quiz', '0014_merge_20251127_2335'),
        ('saas', '0010_licensegrant_question_papers_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('question_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('short_answer', 'Short Answer'), ('match', 'Match the Following'), ('true_false', 'True/False')], max_length=20)),
                ('question_image', models.ImageField(blank=True, help_text='Optional image to accompany the question text.', null=True, upload_to='questions/images/')),
                ('question_text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curriculum_board', models.ForeignKey(blank=True, default=None, limit_choices_to={'node_type': 'board'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_Org_questions', to='curritree.treenode')),
                ('curriculum_chapter', models.ForeignKey(blank=True, default=None, limit_choices_to={'node_type': 'chapter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapter_Org_questions', to='curritree.treenode')),
                ('curriculum_class', models.ForeignKey(blank=True, default=None, limit_choices_to={'node_type': 'class'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_Org_questions', to='curritree.treenode')),
                ('curriculum_subject', models.ForeignKey(blank=True, default=None, limit_choices_to={'node_type': 'subject'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Org_questions', to='curritree.treenode')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.organizationprofile')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='orignal_qid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.orgquestion'),
        ),
    ]
