# Generated by Django 5.2.3 on 2025-11-27 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_orgquestion_question_orignal_qid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillBlankAnswerOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=200)),
                ('is_case_sensitive', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_blank_answers_org', to='quiz.orgquestion')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPairOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_item', models.CharField(max_length=200)),
                ('right_item', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_pairs_org', to='quiz.orgquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MCQOptionOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_options_org', to='quiz.orgquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ShortAnswerOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_answer', models.TextField()),
                ('max_words', models.PositiveIntegerField(default=50)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_answer_org', to='quiz.orgquestion')),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalseAnswerOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.BooleanField()),
                ('explanation', models.TextField(blank=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='true_false_answer_org', to='quiz.orgquestion')),
            ],
        ),
    ]
