# Generated by Django 5.2.3 on 2025-11-28 16:20 (Adjusted manually for data population and integrity)

import uuid
from django.db import migrations, models

def populate_paper_uuids(apps, schema_editor):
    """
    Iterates over existing QuestionPaper objects and assigns a unique UUID
    to the 'paper_uuid' field.
    """
    QuestionPaper = apps.get_model('quiz', 'QuestionPaper')
    
    papers_to_update = []
    # Fetch records where the UUID is currently null (i.e., the existing data)
    for paper in QuestionPaper.objects.filter(paper_uuid__isnull=True):
        paper.paper_uuid = uuid.uuid4()
        papers_to_update.append(paper)
    
    # Use bulk_update for efficiency
    if papers_to_update:
        QuestionPaper.objects.bulk_update(papers_to_update, ['paper_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_fillblankanswerorg_matchpairorg_mcqoptionorg_and_more'),
    ]

    operations = [
        # Step 1: Add the field (Nullable, No Default, No Unique)
        migrations.AddField(
            model_name='questionpaper',
            name='paper_uuid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        
        # Step 2: Populate the new field for existing data (guaranteeing uniqueness)
        migrations.RunPython(populate_paper_uuids, reverse_code=migrations.RunPython.noop),
        
        # Step 3: Add the default UUID for all FUTURE object creations
        migrations.AlterField(
            model_name='questionpaper',
            name='paper_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        
        # Step 4: Safely enforce the unique constraint using AddConstraint.
        # This is often more reliable on populated tables than using AlterField(unique=True).
        migrations.AddConstraint(
            model_name='questionpaper',
            constraint=models.UniqueConstraint(fields=('paper_uuid',), name='unique_questionpaper_uuid'),
        ),
    ]
