# Generated by Django 5.2.3 on 2025-11-28 16:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_questionpaper_paper_uuid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionpaper',
            name='unique_questionpaper_uuid',
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='paper_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
