# Generated by Django 5.2.3 on 2025-12-04 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_remove_questionpaper_unique_questionpaper_uuid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcqoptionorg',
            options={'ordering': ['order'], 'verbose_name': 'Client MCQ', 'verbose_name_plural': 'Client MCQs'},
        ),
        migrations.CreateModel(
            name='PaperOrgQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('marks', models.PositiveIntegerField()),
                ('section', models.CharField(blank=True, max_length=50)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_orgquestions', to='quiz.questionpaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.orgquestion')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('paper', 'question')},
            },
        ),
    ]
