# Generated by Django 5.2.3 on 2025-12-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_alter_mcqoptionorg_options_paperorgquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fillblankanswer',
            options={'verbose_name': 'FIB Question Option', 'verbose_name_plural': 'FIB Question Options'},
        ),
        migrations.AlterModelOptions(
            name='fillblankanswerorg',
            options={'verbose_name': 'Client FIB Question Option', 'verbose_name_plural': 'Client FIB Question Options'},
        ),
        migrations.AlterModelOptions(
            name='matchpair',
            options={'ordering': ['order'], 'verbose_name': 'Match Question Option', 'verbose_name_plural': 'Match Question Options'},
        ),
        migrations.AlterModelOptions(
            name='matchpairorg',
            options={'ordering': ['order'], 'verbose_name': 'Client Match Question Option', 'verbose_name_plural': 'Client Match Question Options'},
        ),
        migrations.AlterModelOptions(
            name='mcqoption',
            options={'ordering': ['order'], 'verbose_name': 'MCQ Question Option', 'verbose_name_plural': 'MCQ Question Options'},
        ),
        migrations.AlterModelOptions(
            name='mcqoptionorg',
            options={'ordering': ['order'], 'verbose_name': 'Client MCQ Question Option', 'verbose_name_plural': 'Client MCQ Question Options'},
        ),
        migrations.AlterModelOptions(
            name='orgquestion',
            options={'ordering': ['-created'], 'verbose_name': 'Client Question ', 'verbose_name_plural': 'Client Question '},
        ),
        migrations.AlterModelOptions(
            name='paperorgquestion',
            options={'ordering': ['order'], 'verbose_name': 'Client Question In Paper', 'verbose_name_plural': 'Client Question In Paper'},
        ),
        migrations.AlterModelOptions(
            name='paperquestion',
            options={'ordering': ['order'], 'verbose_name': 'Question In Paper', 'verbose_name_plural': 'Question In Paper'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created'], 'verbose_name': 'Public Question ', 'verbose_name_plural': 'Public Question '},
        ),
        migrations.AlterModelOptions(
            name='questionpaper',
            options={'ordering': ['-created'], 'verbose_name': 'Question Paper', 'verbose_name_plural': 'Question Paper'},
        ),
        migrations.AlterModelOptions(
            name='questionpaperattempt',
            options={'verbose_name': 'Attempts on Question Paper', 'verbose_name_plural': 'Attempts on Question Paper'},
        ),
        migrations.AlterModelOptions(
            name='questionuploadlog',
            options={'verbose_name': 'Bulk Upload Of Question', 'verbose_name_plural': 'Bulk Upload Of Question'},
        ),
        migrations.AlterModelOptions(
            name='shortanswer',
            options={'verbose_name': ' Short Answer Question Option', 'verbose_name_plural': ' Short Answer Question Options'},
        ),
        migrations.AlterModelOptions(
            name='shortanswerorg',
            options={'verbose_name': 'Client Short Answer Question Option', 'verbose_name_plural': 'Client Short Answer Question Options'},
        ),
        migrations.AlterModelOptions(
            name='truefalseanswer',
            options={'verbose_name': 'True or False Question Option', 'verbose_name_plural': 'True or False Question Options'},
        ),
        migrations.AlterModelOptions(
            name='truefalseanswerorg',
            options={'verbose_name': 'Client True or False Question Option', 'verbose_name_plural': 'Client True or False Question Options'},
        ),
        migrations.AddField(
            model_name='orgquestion',
            name='paere_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='paere_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
