# Generated by Django 5.2.3 on 2025-12-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_alter_fillblankanswer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='marks_distribution',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
