# Generated by Django 5.2.3 on 2025-12-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_questionpaper_marks_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_Textual',
            field=models.BooleanField(default=False),
        ),
    ]
