# Generated by Django 5.2.3 on 2025-12-10 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_question_is_textual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgquestion',
            name='paere_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='paere_count',
        ),
    ]
