# Generated by Django 5.2.3 on 2025-12-11 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curritree', '0003_treenode_marks'),
        ('quiz', '0023_remove_orgquestion_paere_count_and_more'),
        ('saas', '0011_alter_licensepermission_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('match', 'Match the Following (Simple)'), ('short_answer', 'Short Answer (SAQ)'), ('essay', 'Long Answer/Essay (LAQ)'), ('assertion_reason', 'Assertion-Reason'), ('integer_type', 'Numerical/Integer'), ('ordering', 'Sequencing/Ordering'), ('matrix_match', 'Matrix Match')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('match', 'Match the Following (Simple)'), ('short_answer', 'Short Answer (SAQ)'), ('essay', 'Long Answer/Essay (LAQ)'), ('assertion_reason', 'Assertion-Reason'), ('integer_type', 'Numerical/Integer'), ('ordering', 'Sequencing/Ordering'), ('matrix_match', 'Matrix Match')], max_length=20),
        ),
        migrations.CreateModel(
            name='AssertionReasonAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assertion_text', models.TextField()),
                ('reason_text', models.TextField()),
                ('correct_option', models.CharField(choices=[('A', 'Both Assertion and Reason are true and Reason is the correct explanation of Assertion.'), ('B', 'Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.'), ('C', 'Assertion is true but Reason is false.'), ('D', 'Assertion is false but Reason is true.')], max_length=1)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assertion_reason_answer', to='quiz.question')),
            ],
            options={
                'verbose_name': 'Assertion-Reason Answer',
                'verbose_name_plural': 'Assertion-Reason Answers',
            },
        ),
        migrations.CreateModel(
            name='AssertionReasonAnswerOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assertion_text', models.TextField()),
                ('reason_text', models.TextField()),
                ('correct_option', models.CharField(choices=[('A', 'Both Assertion and Reason are true and Reason is the correct explanation of Assertion.'), ('B', 'Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.'), ('C', 'Assertion is true but Reason is false.'), ('D', 'Assertion is false but Reason is true.')], max_length=1)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assertion_reason_answer_org', to='quiz.orgquestion')),
            ],
            options={
                'verbose_name': 'Client Assertion-Reason Answer',
                'verbose_name_plural': 'Client Assertion-Reason Answers',
            },
        ),
        migrations.CreateModel(
            name='IntegerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tolerance', models.DecimalField(decimal_places=4, default=0, help_text="Maximum allowed error margin for the student's answer.", max_digits=10)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integer_answer', to='quiz.question')),
            ],
            options={
                'verbose_name': 'Integer/Numerical Answer',
                'verbose_name_plural': 'Integer/Numerical Answers',
            },
        ),
        migrations.CreateModel(
            name='IntegerAnswerOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tolerance', models.DecimalField(decimal_places=4, default=0, help_text="Maximum allowed error margin for the student's answer.", max_digits=10)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integer_answer_org', to='quiz.orgquestion')),
            ],
            options={
                'verbose_name': 'Client Integer/Numerical Answer',
                'verbose_name_plural': 'Client Integer/Numerical Answers',
            },
        ),
        migrations.CreateModel(
            name='OrderingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(help_text='Text for the item to be sequenced.', max_length=500)),
                ('correct_order_index', models.PositiveIntegerField(help_text='The correct sequential position (e.g., 1, 2, 3...).')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_answers', to='quiz.question')),
            ],
            options={
                'verbose_name': 'Ordering Item',
                'verbose_name_plural': 'Ordering Items',
                'ordering': ['correct_order_index'],
            },
        ),
        migrations.CreateModel(
            name='OrderingAnswerOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(help_text='Text for the item to be sequenced.', max_length=500)),
                ('correct_order_index', models.PositiveIntegerField(help_text='The correct sequential position (e.g., 1, 2, 3...).')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_answers_org', to='quiz.orgquestion')),
            ],
            options={
                'verbose_name': 'Client Ordering Item',
                'verbose_name_plural': 'Client Ordering Items',
                'ordering': ['correct_order_index'],
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('passage_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(help_text='A short title or identifier for the passage/stimulus.', max_length=200)),
                ('passage_text', models.TextField()),
                ('passage_image', models.ImageField(blank=True, help_text='The main diagram, graph, or image that serves as the stimulus for linked questions.', null=True, upload_to='passages/images/')),
                ('is_published', models.BooleanField(default=False, help_text='If true, available to all users/organizations.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curriculum_board', models.ForeignKey(blank=True, default=None, limit_choices_to={'node_type': 'board'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_passages', to='curritree.treenode')),
                ('curriculum_class', models.ForeignKey(blank=True, default=None, limit_choices_to={'node_type': 'class'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_passages', to='curritree.treenode')),
                ('curriculum_subject', models.ForeignKey(blank=True, default=None, limit_choices_to={'node_type': 'subject'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_passages', to='curritree.treenode')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization that owns this private passage.', null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.organizationprofile')),
            ],
            options={
                'verbose_name': 'Reading Passage/Stimulus (Text or Diagram)',
                'verbose_name_plural': 'Reading Passages/Stimuli (Text or Diagram)',
            },
        ),
        migrations.CreateModel(
            name='QuestionSubTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('subtype_name', models.CharField(help_text="The custom name (e.g., 'Case Study MCQ', 'Image Identification').", max_length=500)),
                ('allowed_marks', models.CharField(default='1, 2, 3, 4, 5', help_text="Comma-separated list of valid marks (e.g., '1, 2.5, 5') for questions of this subtype. This enables filtering question subtypes when a user specifies the required mark for a question.", max_length=1000)),
                ('base_question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('match', 'Match the Following (Simple)'), ('short_answer', 'Short Answer (SAQ)'), ('essay', 'Long Answer/Essay (LAQ)'), ('assertion_reason', 'Assertion-Reason'), ('integer_type', 'Numerical/Integer'), ('ordering', 'Sequencing/Ordering'), ('matrix_match', 'Matrix Match')], default='mcq', help_text='The core question format this subtype uses (e.g., MCQ, Short Answer).', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('curriculum_board', models.ForeignKey(blank=True, default=None, help_text='Board scope for this custom subtype (optional).', limit_choices_to={'node_type': 'board'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtype_boards', to='curritree.treenode')),
                ('curriculum_class', models.ForeignKey(blank=True, default=None, help_text='Class scope for this custom subtype (optional).', limit_choices_to={'node_type': 'class'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtype_classes', to='curritree.treenode')),
                ('curriculum_subject', models.ForeignKey(blank=True, default=None, help_text='Subject scope for this custom subtype (optional).', limit_choices_to={'node_type': 'subject'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtype_subjects', to='curritree.treenode')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.organizationprofile')),
            ],
            options={
                'verbose_name': 'Custom Question Subtype',
                'verbose_name_plural': 'Custom Question Subtypes',
                'unique_together': {('curriculum_board', 'curriculum_class', 'curriculum_subject', 'subtype_name', 'base_question_type')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_subtype',
            field=models.ForeignKey(blank=True, help_text="Custom subtype (e.g., 'Case Study Based', 'Diagram Q') for this question.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_questions_with_subtype', to='quiz.questionsubtypes'),
        ),
        migrations.CreateModel(
            name='PassageQuestionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='The order in which the question appears after the passage.')),
                ('org_question', models.ForeignKey(blank=True, help_text='Link to a private (Org) question.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passage_link', to='quiz.orgquestion')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_questions', to='quiz.passage')),
                ('question', models.ForeignKey(blank=True, help_text='Link to a public question.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passage_link', to='quiz.question')),
            ],
            options={
                'verbose_name': 'Passage Question Link',
                'verbose_name_plural': 'Passage Question Links',
                'ordering': ['passage', 'order'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('org_question__isnull', False), ('question__isnull', True)), models.Q(('org_question__isnull', True), ('question__isnull', False)), _connector='OR'), name='must_have_one_question_type')],
            },
        ),
    ]
