# Generated by Django 5.2.3 on 2025-12-11 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_alter_orgquestion_question_type_and_more'),
        ('saas', '0011_alter_licensepermission_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrQuestionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('count', models.IntegerField(default=0, verbose_name='Usage Count')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.organizationprofile')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.orgquestion')),
            ],
            options={
                'verbose_name': 'Organization Question Usage Counter',
                'verbose_name_plural': 'Organization Question Usage Counters',
            },
        ),
        migrations.CreateModel(
            name='QuestionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('count', models.IntegerField(default=0, verbose_name='Usage Count')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.organizationprofile')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
            options={
                'verbose_name': 'Question Usage Counter',
                'verbose_name_plural': 'Question Usage Counters',
            },
        ),
    ]
