# Generated by Django 5.2.3 on 2025-10-03 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curritree', '0002_alter_treenode_node_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The full name of the purchasing entity (e.g., 'Acme Academy').", max_length=255, unique=True, verbose_name='Organization Name')),
                ('billing_email', models.EmailField(max_length=254, unique=True, verbose_name='Primary Contact Email')),
                ('is_active', models.BooleanField(default=True, help_text="Designates if the organization's subscription is currently active.", verbose_name='Subscription Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supported_curriculum', models.ManyToManyField(blank=True, help_text='The top-level curriculum (Boards/Exams) this organization operates under.', limit_choices_to={'node_type__in': ['board', 'competitive']}, related_name='client_supported_curriculums', to='curritree.treenode', verbose_name='Supported Boards/Exams')),
            ],
            options={
                'verbose_name': 'Organization Profile (Tenant)',
                'verbose_name_plural': 'Organization Profiles (Tenants)',
            },
        ),
        migrations.CreateModel(
            name='UsageLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_users', models.PositiveIntegerField(default=50, help_text='Maximum number of active users allowed under this subscription plan.', verbose_name='Maximum Allowed Users')),
                ('organization_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_limit', to='saas.organizationprofile')),
            ],
            options={
                'verbose_name': 'Subscription Usage Limit',
                'verbose_name_plural': 'Subscription Usage Limits',
            },
        ),
        migrations.CreateModel(
            name='LicenseGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_on', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, help_text='Optional date when the license will automatically expire.', null=True, verbose_name='License Expiry Date')),
                ('curriculum_node', models.ForeignKey(help_text='The highest curriculum node (Class/Subject/Unit) to which access is granted (and all its children).', limit_choices_to={'node_type__in': ['class', 'subject', 'unit']}, on_delete=django.db.models.deletion.CASCADE, to='curritree.treenode', verbose_name='Licensed Curriculum Node')),
                ('organization_profile', models.ForeignKey(help_text='The organization that holds this curriculum license.', on_delete=django.db.models.deletion.CASCADE, related_name='license_grants', to='saas.organizationprofile', verbose_name='Client Organization')),
            ],
            options={
                'verbose_name': 'Curriculum License Grant',
                'verbose_name_plural': 'Curriculum License Grants',
                'unique_together': {('organization_profile', 'curriculum_node')},
            },
        ),
    ]
