# Generated by Django 5.2.3 on 2025-10-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curritree', '0002_alter_treenode_node_type'),
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='licensegrant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='usagelimit',
            name='max_users',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of active users allowed under this subscription plan.', verbose_name='Maximum Allowed Users'),
        ),
        migrations.RemoveField(
            model_name='licensegrant',
            name='curriculum_node',
        ),
        migrations.AddField(
            model_name='licensegrant',
            name='curriculum_node',
            field=models.ManyToManyField(blank=True, help_text='The highest curriculum node (Class/Subject/Unit) to which access is granted (and all its children).', limit_choices_to={'node_type__in': ['class', 'subject', 'board', 'competitive']}, to='curritree.treenode', verbose_name='Licensed Curriculum Node'),
        ),
    ]
