# Generated by Django 5.2.3 on 2025-10-13 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('saas', '0002_alter_licensegrant_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='saas.licensegrant')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'unique_together': {('license', 'permission')},
            },
        ),
    ]
