# Generated by Django 5.2.3 on 2025-10-15 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('saas', '0003_licensepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensegrant',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='The specific Django permissions granted by this license.', through='saas.LicensePermission', to='auth.permission', verbose_name='Assigned Permissions'),
        ),
        migrations.AlterField(
            model_name='licensepermission',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LicensePermission', to='saas.licensegrant'),
        ),
    ]
