# Generated by Django 5.2.3 on 2025-10-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0004_licensegrant_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelimit',
            name='max_question_papers',
            field=models.PositiveIntegerField(default=50, help_text='Maximum number of question papers this organization can generate.', verbose_name='Maximum Question Papers'),
        ),
    ]
