# Generated by Django 5.2.3 on 2025-10-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0005_usagelimit_max_question_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Organization Address'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact Phone Number'),
        ),
    ]
