# Generated by Django 5.2.3 on 2025-10-27 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('saas', '0006_organizationprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_groups', to='saas.organizationprofile', verbose_name='Organization')),
                ('permissions', models.ManyToManyField(blank=True, related_name='organization_groups', to='auth.permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Organization Group',
                'verbose_name_plural': 'Organization Groups',
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
