# Generated by Django 5.2.3 on 2025-10-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organizationgroup_alter_profile_organization_groups'),
        ('saas', '0007_organizationgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationGroup',
        ),
    ]
