# Generated by Django 5.2.3 on 2025-10-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0008_delete_organizationgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usagelimit',
            name='max_question_papers',
        ),
        migrations.AddField(
            model_name='licensegrant',
            name='max_question_papers',
            field=models.PositiveIntegerField(default=50, help_text='Maximum number of question papers this organization can generate.', verbose_name='Maximum Question Papers'),
        ),
        migrations.AddField(
            model_name='usagelimit',
            name='max_question_papers_drafts',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of question papers drafts this organization can generate.', verbose_name='Maximum Question Papers Drafts'),
        ),
    ]
