# Generated by Django 5.2.3 on 2025-11-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0009_remove_usagelimit_max_question_papers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensegrant',
            name='question_papers_created',
            field=models.PositiveIntegerField(default=0, help_text='number of question papers this organization has generate.', verbose_name='No Of Question Papers created'),
        ),
    ]
