# Generated by Django 5.2.3 on 2025-12-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0010_licensegrant_question_papers_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licensepermission',
            options={'verbose_name': 'License', 'verbose_name_plural': 'License'},
        ),
    ]
