# Generated by Django 5.2.3 on 2025-09-06 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('education', '0001_initial'),
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.board'),
        ),
        migrations.AddField(
            model_name='profile',
            name='class_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.studentclass'),
        ),
        migrations.AddField(
            model_name='profile',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.division'),
        ),
        migrations.AddField(
            model_name='profile',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.institution'),
        ),
        migrations.AddField(
            model_name='profile',
            name='institute_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.institutiongroup'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
