# Generated by Django 5.2.3 on 2025-10-03 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_created_alter_profile_modified_and_more'),
        ('curritree', '0002_alter_treenode_node_type'),
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='board',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='class_field',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='division',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='institute_group',
        ),
        migrations.AddField(
            model_name='profile',
            name='academic_stream',
            field=models.ForeignKey(blank=True, limit_choices_to={'node_type__in': ['board', 'competitive', 'class', 'subject']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curritree.treenode', verbose_name='Academic Stream/Content Boundary'),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saas.organizationprofile', verbose_name='Client Organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Staff'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
