# Generated by Django 5.2.3 on 2025-10-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_board_remove_profile_class_field_and_more'),
        ('curritree', '0002_alter_treenode_node_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='academic_stream',
        ),
        migrations.AddField(
            model_name='profile',
            name='academic_stream',
            field=models.ManyToManyField(blank=True, limit_choices_to={'node_type__in': ['board', 'competitive', 'class', 'subject']}, to='curritree.treenode', verbose_name='Academic Stream/Content Boundary'),
        ),
    ]
