# Generated by Django 5.2.3 on 2025-10-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_academic_stream_and_more'),
        ('saas', '0007_organizationgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization_groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='saas.organizationgroup', verbose_name='Organization Groups'),
        ),
    ]
