# Generated by Django 5.2.3 on 2025-11-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organizationgroup_alter_profile_organization_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Surname',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional. Used for alternate login or two-factor authentication.', max_length=20, null=True, unique=True),
        ),
    ]
