# Generated by Django 5.2.3 on 2025-11-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_name_remove_profile_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='impersonation_pin',
            field=models.CharField(blank=True, default=12345, help_text='A security PIN required for staff/admin users (non-superusers) to impersonate this user. Use a hashing function before saving in production.', max_length=128, null=True),
        ),
    ]
