# Generated by Django 5.2.3 on 2025-11-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_impersonation_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_license_active',
            field=models.BooleanField(default=True, help_text="Indicates if the user's license is currently active."),
        ),
    ]
