# Generated by Django 5.2.3 on 2025-12-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_is_license_active'),
        ('curritree', '0003_treenode_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='academic_stream',
            field=models.ManyToManyField(blank=True, limit_choices_to={'node_type__in': ['board', 'competitive', 'class', 'subject', 'chapter', 'unit', 'section']}, to='curritree.treenode', verbose_name='Academic Stream/Content Boundary'),
        ),
    ]
