# Generated by Django 5.2.3 on 2025-12-04 17:42
# NOTE: Please ensure the filename matches the sequence, e.g., 0012_cleanup_saas_duplicates.py

from django.db import migrations


def clean_up_duplicate_permissions(apps, schema_editor):
    """
    Deletes the stale ContentType and associated Permissions for 
    'organizationgroup' that incorrectly exist under the 'saas' app label.
    This resolves the issue of having duplicate OrganizationGroup permissions 
    in your permission listing (one for 'accounts', one for 'saas').
    """
    # Get the necessary models from the Apps registry
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    
    # 1. Identify the incorrect ContentType (App Label: 'saas', Model Name: 'organizationgroup')
    try:
        incorrect_ct = ContentType.objects.get(app_label='saas', model='organizationgroup')
    except ContentType.DoesNotExist:
        # If it doesn't exist, the cleanup is already done or the data is different.
        return

    # 2. Delete all permissions linked to that incorrect ContentType
    Permission.objects.filter(content_type=incorrect_ct).delete()

    # 3. Delete the ContentType itself
    incorrect_ct.delete()


class Migration(migrations.Migration):

    dependencies = [
        # This dependency must point to the last migration in the accounts app
        ('accounts', '0011_alter_profile_academic_stream'),
    ]

    operations = [
        migrations.RunPython(clean_up_duplicate_permissions, migrations.RunPython.noop),
    ]