# Generated by Django 5.2.3 on 2025-12-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20251204_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationgroup',
            options={'verbose_name': 'Client Group', 'verbose_name_plural': 'Client Group'},
        ),
    ]
